### ISSUE TITLE
WATS running out of disk space

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry/garden-windows#16]
From @bdshroyer (moving this issue from WAL)

Hello all,

WATS recently failed on multiple container creation failures. Examining the cell logs, we found that the VM was running out of disk space. We checked bosh vms --vitals and found that our two Windows cells had 73% and 97% disk usage, respectively.

Looking at the cells themselves, it looks like the bulk of the disk space is being used by the Windows folder, with the WinSxS subfolder taking up a disproportionate share (about half or so).

Thanks,

Brandon

**Comment by sunjayBhatia** [comment]
```
Containerizer    [ERROR] 04/14 20:37:46.31            unhandled exception
                                                      {"arguments":{"spec":{"bind_mounts":[{"dst_path":"/tmp/lifecycle","mode":0,"src_path":"\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d"}],"env":["INSTANCE_GUID=ed1cf892-49bb-4491-58ba-0da023d7e3a0","INSTANCE_INDEX=3","CF_INSTANCE_GUID=ed1cf892-49bb-4491-58ba-0da023d7e3a0","CF_INSTANCE_INDEX=3","LANG=en_US.UTF-8"],
"grace_time":3e+11,"handle":"ed1cf892-49bb-4491-58ba-0da023d7e3a0","limits":{"cpu_limits":{"limit_in_shares":256},"disk_limits":{"byte_hard":1.073741824e+09},"memory_limits":{"limit_in_bytes":2.147483648e+09}},
"properties":{"executor:owner":"executor","network.app_id":"4d0f4d6b-6d77-441a-b8a6-d76009b3abba","network.org_id":"c81926c1-77ad-4162-a5e6-3268fa48987c",
"network.policy_group_id":"4d0f4d6b-6d77-441a-b8a6-d76009b3abba","network.space_id":"c155c5f6-c14f-4b09-97a3-dfd5c8ffe259"}}},
"exception":{"ClassName":"System.IO.IOException","Data":{"c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\config\\application_host.config":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\config\\web.config":"There is not enough space on the disk.\r\n",
"c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\diego-sshd.exe":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\healthcheck.exe":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\newtonsoft.json.xml":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tar.exe":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\app_global.asax.dbvtead8.dll":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\assembly\\dl3\\4bfe0e73\\e0d96c1e_4c82d201\\system.net.http.formatting.dll":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\assembly\\dl3\\6411d79f\\e0d96c1e_4c82d201\\newtonsoft.json.dll":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\assembly\\dl3\\7cf4ed04\\49dc6d1e_4c82d201\\system.web.http.web_host.dll":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\assembly\\dl3\\b65d9e7b\\49dc6d1e_4c82d201\\system.web.http.dll":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\assembly\\dl3\\b8c2d3d7\\e0d96c1e_4c82d201\\nora.dll":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\hash":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\user_cache":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\web_app_server.exe":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\yaml_dot_net.dll":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\yaml_dot_net.pdb":"There is not enough space on the disk.\r\n","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\yaml_dot_net.xml":"There is not enough space on the disk.\r\n",
"c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\zlib1.dll":"There is not enough space on the disk.\r\n"},"ExceptionMethod":"8\nFxCopyOrMoveDirectory\nMicrosoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=<FOO>\nMicrosoft.VisualBasic.FileIO.FileSystem\nVoid FxCopyOrMoveDirectory(CopyOrMove, System.String, System.String, Boolean)","HResult":-2.1462328e+09,"HelpURL":null,"InnerException":null,"Message":"Could not complete operation on some files and directories. See the Data property of the exception for more details.","RemoteStackIndex":0,"RemoteStackTraceString":null,"Source":"Microsoft.VisualBasic","StackTraceString":"   at Microsoft.VisualBasic.FileIO.FileSystem.FxCopyOrMoveDirectory(CopyOrMove operation, String sourceDirectoryPath, String targetDirectoryPath, Boolean overwrite)\r\n   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveDirectory(CopyOrMove operation, String sourceDirectoryName, String destinationDirectoryName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)\r\n   at IronFrame.Utilities.PlatformFileSystem.CopyDirectory(String sourceDirectory, String destinationDirectory, Boolean overwrite) in c:\\garden-windows-release\\src\\code.cloudfoundry.org\\garden-windows\\Containerizer\\IronFrame\\IronFrame\\Utilities\\FileSystemManager.cs:line 22\r\n   at IronFrame.Utilities.FileSystemManager.Copy(String source, String destination) in c:\\garden-windows-release\\src\\code.cloudfoundry.org\\garden-windows\\Containerizer\\IronFrame\\IronFrame\\Utilities\\FileSystemManager.cs:line 206\r\n   at IronFrame.ContainerDirectory.CreateBindMounts(BindMount[] bindMounts, IContainerUser containerUser) in c:\\garden-windows-release\\src\\code.cloudfoundry.org\\garden-windows\\Containerizer\\IronFrame\\IronFrame\\ContainerDirectory.cs:line 157\r\n   at IronFrame.ContainerService.CreateContainer(ContainerSpec containerSpec) in c:\\garden-windows-release\\src\\code.cloudfoundry.org\\garden-windows\\Containerizer\\IronFrame\\IronFrame\\ContainerService.cs:line 155\r\n   at Containerizer.Controllers.ContainersController.Create(ContainerSpecApiModel spec) in c:\\garden-windows-release\\src\\code.cloudfoundry.org\\garden-windows\\Containerizer\\Containerizer\\Controllers\\ContainersController.cs:line 97\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.\u003c\u003ec__DisplayClass10.\u003cGetExecutor\u003eb__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.\u003cInvokeActionAsyncCore\u003ed__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.\u003cCallOnActionExecutedAsync\u003ed__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.\u003cCallOnActionExecutedAsync\u003ed__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.\u003cExecuteActionFilterAsyncCore\u003ed__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.\u003cExecuteAsync\u003ed__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.\u003cExecuteAsync\u003ed__0.MoveNext()","WatsonBuckets":null},"method":"POST","route_template":"api/containers","uri":"http://localhost:1788/api/containers"}
```

From the cell's BOSH logs

**Comment by sunjayBhatia** [comment]
When we try to create bind mounts (copy buildpacks/WAL into the container directory) and there is not enough space on disk, we don't handle the exception properly.

**Comment by pnikonowicz** [comment]
Here's a more formatted view of the log:
```
Containerizer    [ERROR] 04/14 20:37:46.31            unhandled exception
                                                      {"arguments":{"spec":{"bind_mounts":[{"dst_path":"/tmp/lifecycle","mode":0,"src_path":"\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d"}],"env":["INSTANCE_GUID=ed1cf892-49bb-4491-58ba-0da023d7e3a0","INSTANCE_INDEX=3","CF_INSTANCE_GUID=ed1cf892-49bb-4491-58ba-0da023d7e3a0","CF_INSTANCE_INDEX=3","LANG=en_US.UTF-8"],
"grace_time":3e+11,"handle":"ed1cf892-49bb-4491-58ba-0da023d7e3a0","limits":{"cpu_limits":{"limit_in_shares":256},"disk_limits":{"byte_hard":1.073741824e+09},"memory_limits":{"limit_in_bytes":2.147483648e+09}},
"properties":{"executor:owner":"executor","network.app_id":"4d0f4d6b-6d77-441a-b8a6-d76009b3abba","network.org_id":"c81926c1-77ad-4162-a5e6-3268fa48987c",
"network.policy_group_id":"4d0f4d6b-6d77-441a-b8a6-d76009b3abba","network.space_id":"c155c5f6-c14f-4b09-97a3-dfd5c8ffe259"}}},
"exception":{"ClassName":"System.IO.IOException","Data":{"c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\config\\application_host.config":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\config\\web.config":"There is not enough space on the disk.
",
"c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\diego-sshd.exe":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\healthcheck.exe":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\newtonsoft.json.xml":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tar.exe":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\app_global.asax.dbvtead8.dll":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\assembly\\dl3\\4bfe0e73\\e0d96c1e_4c82d201\\system.net.http.formatting.dll":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\assembly\\dl3\\6411d79f\\e0d96c1e_4c82d201\\newtonsoft.json.dll":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\assembly\\dl3\\7cf4ed04\\49dc6d1e_4c82d201\\system.web.http.web_host.dll":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\assembly\\dl3\\b65d9e7b\\49dc6d1e_4c82d201\\system.web.http.dll":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\assembly\\dl3\\b8c2d3d7\\e0d96c1e_4c82d201\\nora.dll":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\hash":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\tmp\\root\\8d22ca0b\\62d849c9\\user_cache":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\web_app_server.exe":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\yaml_dot_net.dll":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\yaml_dot_net.pdb":"There is not enough space on the disk.
","c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\yaml_dot_net.xml":"There is not enough space on the disk.
",
"c:\\var\\vcap\\data\\executor_cache\\99cff2d142a32ee28e7cfbd44fe75a46-1491506067418589500-1581.d\\zlib1.dll":"There is not enough space on the disk.
"},"ExceptionMethod":"8\nFxCopyOrMoveDirectory\nMicrosoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=<FOO>\nMicrosoft.VisualBasic.FileIO.FileSystem\nVoid FxCopyOrMoveDirectory(CopyOrMove, System.String, System.String, Boolean)","HResult":-2.1462328e+09,"HelpURL":null,"InnerException":null,"Message":"Could not complete operation on some files and directories. See the Data property of the exception for more details.","RemoteStackIndex":0,"RemoteStackTraceString":null,"Source":"Microsoft.VisualBasic","StackTraceString":"   at Microsoft.VisualBasic.FileIO.FileSystem.FxCopyOrMoveDirectory(CopyOrMove operation, String sourceDirectoryPath, String targetDirectoryPath, Boolean overwrite)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveDirectory(CopyOrMove operation, String sourceDirectoryName, String destinationDirectoryName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)
   at IronFrame.Utilities.PlatformFileSystem.CopyDirectory(String sourceDirectory, String destinationDirectory, Boolean overwrite) in c:\\garden-windows-release\\src\\code.cloudfoundry.org\\garden-windows\\Containerizer\\IronFrame\\IronFrame\\Utilities\\FileSystemManager.cs:line 22
   at IronFrame.Utilities.FileSystemManager.Copy(String source, String destination) in c:\\garden-windows-release\\src\\code.cloudfoundry.org\\garden-windows\\Containerizer\\IronFrame\\IronFrame\\Utilities\\FileSystemManager.cs:line 206
   at IronFrame.ContainerDirectory.CreateBindMounts(BindMount[] bindMounts, IContainerUser containerUser) in c:\\garden-windows-release\\src\\code.cloudfoundry.org\\garden-windows\\Containerizer\\IronFrame\\IronFrame\\ContainerDirectory.cs:line 157
   at IronFrame.ContainerService.CreateContainer(ContainerSpec containerSpec) in c:\\garden-windows-release\\src\\code.cloudfoundry.org\\garden-windows\\Containerizer\\IronFrame\\IronFrame\\ContainerService.cs:line 155
   at Containerizer.Controllers.ContainersController.Create(ContainerSpecApiModel spec) in c:\\garden-windows-release\\src\\code.cloudfoundry.org\\garden-windows\\Containerizer\\Containerizer\\Controllers\\ContainersController.cs:line 97
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.\u003c\u003ec__DisplayClass10.\u003cGetExecutor\u003eb__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.\u003cInvokeActionAsyncCore\u003ed__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.\u003cCallOnActionExecutedAsync\u003ed__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.\u003cCallOnActionExecutedAsync\u003ed__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.\u003cExecuteActionFilterAsyncCore\u003ed__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.\u003cExecuteAsync\u003ed__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.\u003cExecuteAsync\u003ed__0.MoveNext()","WatsonBuckets":null},"method":"POST","route_template":"api/containers","uri":"http://localhost:1788/api/containers"}
From t

```

**Comment by pnikonowicz** [comment]
Why is Diego asking us to create a container when we do not have enough space to do so? Is this a problem with Diego or Resource Reporting?

**Comment by sunjayBhatia** [comment]
the proposed solution is to solve this with ephemeral disk support in Windows stemcells, `C:\var\vcap\data` should not really be on the root disk, it should be on a mounted ephemeral disk
